import = ["~/.config/alacritty/catppuccin-mocha.toml"]

########
# FONT #
########

[font]

# Normal font style
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }

size = 14

[env]

TERM = "xterm-256color"


